import { useEffect, useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { translations } from './data/portfolio';
import { Navbar, Hero, Process, About, Projects, Skills, Contact, ProjectModal } from './components/Sections';
import './styles.css';
import './social-update.css';
import './contact-about-refinement.css';
import './interaction-refinement.css';
export default function App(){const [theme,setTheme]=useState(localStorage.getItem('portfolio-theme')||'dark');const [lang,setLang]=useState(localStorage.getItem('portfolio-lang')||'pt');const [project,setProject]=useState(null);useEffect(()=>{document.body.dataset.theme=theme;localStorage.setItem('portfolio-theme',theme)},[theme]);useEffect(()=>localStorage.setItem('portfolio-lang',lang),[lang]);useEffect(()=>{const close=e=>e.key==='Escape'&&setProject(null);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{const orbit=document.querySelector('.orbit');const aboutImage=document.querySelector('.about-visual img');if(orbit){gsap.to(orbit,{x:72,y:260,rotation:10,opacity:.35,ease:'none',scrollTrigger:{trigger:'.app',start:'top top',end:'bottom bottom',scrub:1}})}if(aboutImage){gsap.fromTo(aboutImage,{rotationY:-8,opacity:.72},{rotationY:8,opacity:1,ease:'none',scrollTrigger:{trigger:'.about-visual',start:'top 90%',end:'bottom 15%',scrub:1}})}gsap.utils.toArray('.project-card').forEach((card,index)=>{gsap.fromTo(card,{y:36,opacity:0},{y:0,opacity:1,duration:.7,delay:index*.06,ease:'power2.out',scrollTrigger:{trigger:card,start:'top 88%',once:true}})});gsap.utils.toArray('.process-grid article').forEach((card,index)=>{gsap.fromTo(card,{y:24,opacity:0},{y:0,opacity:1,duration:.55,delay:index*.06,ease:'power2.out',scrollTrigger:{trigger:card,start:'top 90%',once:true}})})});return()=>ctx.revert()},[]);const t=translations[lang];return <div className="app"><Navbar {...{lang,setLang,theme,setTheme}}/><main><Hero t={t}/><Process/><About/><Projects onOpen={setProject}/><Skills/><Contact/></main><footer>© {new Date().getFullYear()} Kauã Tojal · Desenvolvido com React, Vite e JavaScript.</footer><a className="top" href="#home" aria-label="Voltar ao topo">↑</a><ProjectModal project={project} onClose={()=>setProject(null)}/></div>}
